# Generated by Django 4.1.7 on 2023-04-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('has_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaidUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='telegram_bot.unpaiduser')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_day', models.DateField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('пол', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
                ('цель', models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=1)),
                ('место', models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=1)),
                ('уровень', models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=1)),
            ],
        ),
    ]
