# Generated by Django 4.1.7 on 2023-04-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.PositiveIntegerField()),
                ('day2', models.PositiveIntegerField()),
                ('day3', models.PositiveIntegerField()),
                ('day4', models.PositiveIntegerField()),
                ('day5', models.PositiveIntegerField()),
                ('day6', models.PositiveIntegerField()),
                ('day7', models.PositiveIntegerField()),
                ('day8', models.PositiveIntegerField()),
                ('day9', models.PositiveIntegerField()),
                ('day10', models.PositiveIntegerField()),
                ('day11', models.PositiveIntegerField()),
                ('day12', models.PositiveIntegerField()),
                ('day13', models.PositiveIntegerField()),
                ('day14', models.PositiveIntegerField()),
                ('day15', models.PositiveIntegerField()),
                ('day16', models.PositiveIntegerField()),
                ('day17', models.PositiveIntegerField()),
                ('day18', models.PositiveIntegerField()),
                ('day19', models.PositiveIntegerField()),
                ('day20', models.PositiveIntegerField()),
                ('day21', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.paiduser')),
            ],
        ),
    ]
