# Generated by Django 4.1.7 on 2023-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_usercalories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiduser',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
