# Generated by Django 4.1.7 on 2023-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_paiduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiduser',
            name='место',
            field=models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='пол',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=7),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='уровень',
            field=models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=16),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='цель',
            field=models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=12),
        ),
    ]
