# Generated by Django 4.1.7 on 2023-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_bankcards_number_of_activations'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiduser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
