# Generated by Django 4.1.7 on 2023-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_paiduser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedUser',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_day', models.DateField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('пол', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=7)),
                ('цель', models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=12)),
                ('место', models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=3)),
                ('уровень', models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=16)),
            ],
        ),
    ]
