# Generated by Django 4.1.7 on 2023-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0009_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalories",
            name="day10_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day11_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day12_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day13_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day14_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day15_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day16_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day17_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day18_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day19_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day1_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day20_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day21_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day2_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day3_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day4_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day5_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day6_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day7_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day8_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercalories",
            name="day9_requested",
            field=models.BooleanField(default=False),
        ),
    ]
