# Generated by Django 4.1.7 on 2023-06-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_alter_courseday_total_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finisheduser',
            name='proteins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
