# Generated by Django 4.1.7 on 2023-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_paiduser_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='has_requested',
            field=models.BooleanField(default=False),
        ),
    ]
