# Generated by Django 4.1.7 on 2023-04-12 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Категории',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('пол', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
                ('цель', models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=1)),
                ('место', models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=1)),
                ('уровень', models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('content_type', models.CharField(choices=[('V', 'Video'), ('T', 'Text'), ('P', 'Photo'), ('G', 'GIF')], default='T', max_length=1)),
                ('text', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence_number', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_contents', to='courses.категории')),
            ],
            options={
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('content_type', models.CharField(choices=[('V', 'Video'), ('T', 'Text'), ('P', 'Photo'), ('G', 'GIF')], default='T', max_length=1)),
                ('text', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence_number', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_contents', to='courses.категории')),
            ],
            options={
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
    ]
