# Generated by Django 4.1.7 on 2023-04-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycontent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='specialcontent',
            name='text',
        ),
    ]
