# Generated by Django 4.1.7 on 2023-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_dailycontent_text_remove_specialcontent_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='категории',
            name='место',
            field=models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='категории',
            name='пол',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=7),
        ),
        migrations.AlterField(
            model_name='категории',
            name='уровень',
            field=models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=16),
        ),
        migrations.AlterField(
            model_name='категории',
            name='цель',
            field=models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=12),
        ),
    ]
