# Generated by Django 4.1.7 on 2023-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_категории_место_alter_категории_пол_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycontent',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialcontent',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
