# Generated by Django 4.1.7 on 2023-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_unpaidusercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycontent',
            name='gif_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dailycontent',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dailycontent',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specialcontent',
            name='gif_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specialcontent',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specialcontent',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidusercontent',
            name='gif_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidusercontent',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unpaidusercontent',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
