# Generated by Django 4.1.7 on 2023-04-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_dailycontent_gif_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaidusercontent',
            name='unpaid_user',
        ),
        migrations.DeleteModel(
            name='SpecialContent',
        ),
    ]
