# Generated by Django 4.1.7 on 2023-05-03 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_dailycontent_video_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('content_type', models.CharField(choices=[('V', 'Video'), ('T', 'Text'), ('P', 'Photo'), ('G', 'GIF')], default='T', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('video_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('photo_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('gif_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Тренировки', to='courses.категории')),
            ],
            options={
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('content_type', models.CharField(choices=[('V', 'Video'), ('T', 'Text'), ('P', 'Photo'), ('G', 'GIF')], default='T', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gifs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('video_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('photo_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('gif_file_id', models.CharField(blank=True, max_length=300, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Рассылка', to='courses.категории')),
            ],
            options={
                'ordering': ['sequence_number'],
                'abstract': False,
            },
        ),
    ]
